# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171210_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
